Create bot to fetch images from a Discord channel of all threads
kommitters/bas pull request #102
Opened 2024-09-20 21:57 UTC by LuchoAravena

2024-09-26 21:07 UTC, FelipeGuzmanSierra requested changes
Great work! Just some comments

2024-09-26 21:07 UTC, FelipeGuzmanSierra commented on lib/bas/bot/fetch_images_from_discord.rb
> +    # Process function to execute the Discord utility to fetch images from a discord channel threads
What do you think about changing it to `Process function to execute the Discord utility to fetch images from Discord channel threads.`? :thinking:

2024-09-26 21:07 UTC, FelipeGuzmanSierra commented on lib/bas/bot/write_media_review_in_discord.rb
> +    # process function to execute the Discord utility to send image feedback to a thread of Discord channel
What do you think about changing it to `process function to execute the Discord utility to send image feedback to a thread of a Discord channel.`? :thinking:

2024-10-02 13:25 UTC, LuchoAravena commented on lib/bas/utils/discord/request.rb
> +      def self.get_thread_messages(params)
We spoke about discard this comment to implement new logic of discord_bot

2024-10-02 13:25 UTC, LuchoAravena commented on lib/bas/utils/discord/request.rb
> +        thread_ids = messages.select { |msg| msg["type"] == 18 }.map { |msg| msg["id"] }
We spoke about discard this comment to implement new logic of discord_bot

2024-10-02 13:26 UTC, LuchoAravena commented on lib/bas/utils/discord/request.rb
> +            next unless (current_time - message_time) < 60 && message["attachments"]
We spoke about discard this comment to implement new logic of discord_bot

2024-10-02 13:28 UTC, LuchoAravena commented on lib/bas/utils/discord/request.rb
> +        HTTParty.get(url, { headers: })
Rubocop's suggested me to remove blank spaces

2024-10-02 13:29 UTC, LuchoAravena commented on lib/bas/utils/discord/request.rb
> +        HTTParty.send(params[:method], url, { body: params[:body].to_json, headers: })
Same here, Rubocop suggested me to remove blank spaces

2024-10-03 21:21 UTC, merged