Solve #83 - Add bots to check webs availability
kommitters/bas pull request #86
Opened 2024-07-17 17:04 UTC by FelipeGuzmanSierra

## Description
On this PR, the bots for the check website availability were added. Fort this:
- FetchDomainServicesFromNotion bot added.
- WriteDomainReviewRequests bot added
- ReviewDomainAvailability bot added

Closes #83 

### Example of use
```ruby
connection = {
  host: "localhost",
  port: 5432,
  dbname: "bas",
  user: "postgres",
  password: "postgres"
}

# # FETCH DOMAINS
options = {
  process_options: {
    database_id: "notion database id",
    secret: "notion secret"
  },
  write_options: {
    connection:,
    db_table: "web_availability",
    tag: "FetchDomainServicesFromNotion"
  }
}

bot = Bot::FetchDomainServicesFromNotion.new(options)
bot.execute

# # WRITE DOMAIN REVIEW REQUESTS
options = {
  read_options: {
    connection:,
    db_table: "web_availability",
    tag: "FetchDomainServicesFromNotion"
  },
  process_options: {
    connection:,
    db_table: "web_availability",
    tag: "ReviewDomainRequest"
  },
  write_options: {
    connection:,
    db_table: "web_availability",
    tag: "WriteDomainReviewRequests"
  }
}

bot = Bot::WriteDomainReviewRequests.new(options)
bot.execute

# # REVIEW: DOMAIN AVAILABILITY

options = {
  read_options: {
    connection:,
    db_table: "web_availability",
    tag: "ReviewDomainRequest"
  },
  write_options: {
    connection:,
    db_table: "web_availability",
    tag: "ReviewDomainAvailability"
  }
}

bot = Bot::ReviewDomainAvailability.new(options)
bot.execute
```

2024-07-17 23:39 UTC, L-Zuluaga requested changes

2024-07-17 23:39 UTC, L-Zuluaga commented on lib/bas/bot/review_domain_availability.rb
> +    # process function to execute the OpenaAI utility to process the media reviews
Is this the correct description? 😅

2024-07-17 23:39 UTC, L-Zuluaga commented on spec/bas/bot/fetch_domain_services_from_notion_spec.rb
> +    it "returns a success hash with the list of formatted ptos" do
Is this the correct description?

2024-07-17 23:39 UTC, L-Zuluaga commented on lib/bas/bot/fetch_domain_services_from_notion.rb
> +  # domains from a notion database and write them on a PostgresDB table with a specific format.
What do you think?
```suggestion
  # web domains from a notion database and write them on a PostgresDB table with a specific format.
```

2024-07-17 23:39 UTC, L-Zuluaga commented on spec/bas/bot/format_do_bill_alert_spec.rb
Is this file required?

2024-07-17 23:39 UTC, L-Zuluaga commented on lib/bas/bot/fetch_domain_services_from_notion.rb
> +    # Process function to execute the Notion utility to fetch domains from a notion database
What do you think?
```suggestion
    # Process function to execute the Notion utility to fetch web domains from a notion database
```

2024-07-18 19:28 UTC, FelipeGuzmanSierra commented on spec/bas/bot/format_do_bill_alert_spec.rb
Hello @L-Zuluaga, yes, is not related to the use case, but it was a test that was failing because the mean calculated on the digital ocean bot changed every day depending on the day of the month. I added a fix to the test in this PR because was a small change.

2024-07-18 19:38 UTC, L-Zuluaga approved these changes

2024-07-18 19:40 UTC, merged